name: 部署到服务器（Caddy 反向代理）
on:
  push:
    branches: [ main ]  # 推送 main 分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 拉取仓库代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 安装 Node.js 环境
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x  # 与你的项目 Node 版本一致

      # 构建前端项目（生成静态文件）
      - name: 构建前端
        run: |
          cd frontend
          npm install
          npm run build  # 生成 dist 文件夹

      # 安装后端生产依赖
      - name: 准备后端
        run: |
          cd backend
          npm install --production  # 只安装生产依赖

      # 通过 SSH 部署到服务器
      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          
          # 部署脚本（根据服务器实际路径修改）
          script: |
            # 服务器项目根目录（提前创建好）
            PROJECT_DIR="/var/www/programming-tools"
            
            # 创建目录（如果不存在）
            mkdir -p $PROJECT_DIR/frontend $PROJECT_DIR/backend
            
            # 清理旧文件
            rm -rf $PROJECT_DIR/frontend/dist
            rm -rf $PROJECT_DIR/backend/*
            
            # 复制新文件到服务器（从 GitHub Actions 工作目录）
            cp -r /github/workspace/frontend/dist $PROJECT_DIR/frontend/
            cp -r /github/workspace/backend/* $PROJECT_DIR/backend/
            
            # 重启后端服务（使用 pm2 管理）
            cd $PROJECT_DIR/backend
            npm install -g pm2  # 确保 pm2 已安装
            pm2 restart app.js || pm2 start app.js  # 重启或启动服务
            
            # 重启 Caddy（使配置生效）
            sudo systemctl restart caddy