name: 部署到服务器（Caddy 反向代理）
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 拉取代码：GitHub Actions 会自动把仓库拉到 /github/workspace（对应你 Codespace 的 /workspaces/ptools）
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # 关键：构建前端——路径与你 Codespace 一致，都是仓库根目录下的 frontend
      - name: 构建前端
        run: |
          cd /github/workspace/frontend  # 明确指定路径，避免歧义（等同于你 Codespace 的 /workspaces/ptools/frontend）
          npm install
          npm run build  # 确保执行后会生成 dist 文件夹

      # 关键：准备后端——路径与你 Codespace 一致
      - name: 准备后端
        run: |
          cd /github/workspace/backend  # 等同于你 Codespace 的 /workspaces/ptools/backend
          npm install --production

      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            PROJECT_DIR="/var/www/programming-tools"
            # 确保服务器目录存在
            mkdir -p $PROJECT_DIR/frontend $PROJECT_DIR/backend
            
            # 清理旧文件
            rm -rf $PROJECT_DIR/frontend/dist
            rm -rf $PROJECT_DIR/backend/*
            
            # 复制文件：路径与 GitHub Actions 拉取的代码路径一致（/github/workspace 对应你 Codespace 的 /workspaces/ptools）
            cp -r /github/workspace/frontend/dist $PROJECT_DIR/frontend/
            cp -r /github/workspace/backend/* $PROJECT_DIR/backend/
            
            # 启动后端：先确认入口文件
            cd $PROJECT_DIR/backend
            npm install -g pm2
            # 关键：确认后端入口文件是 app.js（若不是，替换成 server.js 等实际名称）
            pm2 restart app.js || pm2 start app.js
            
            # 重启 Caddy
            sudo systemctl restart caddy