name: 最终部署（彻底解决目录嵌套）
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'

      - name: 构建前端（确保 dist 非空）
        run: |
          cd frontend
          npm install
          npm run build
          if [ $(ls -A "dist" | wc -l) -eq 0 ]; then
            echo "错误：dist 目录为空"
            exit 1
          fi

      # 关键：先删除服务器上所有旧嵌套目录（彻底清根）
      - name: 清理服务器旧嵌套目录
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 删除前端嵌套的 frontend 目录
            rm -rf /var/www/programming-tools/frontend/frontend
            # 删除后端可能嵌套的 backend 目录
            rm -rf /var/www/programming-tools/backend/backend
            # 确保目标目录存在
            mkdir -p /var/www/programming-tools/frontend /var/www/programming-tools/backend

      # 前端传输：传 dist 内所有内容，直接放到 frontend 目录下（无嵌套）
      - name: 传输前端文件（无嵌套）
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "frontend/dist/*"  # 只传 dist 里的内容（index.html、assets 等）
          target: "/var/www/programming-tools/frontend"  # 内容直接落地到 frontend

      # 后端传输：传 backend 内所有内容，直接放到 backend 目录下（无嵌套）
      - name: 传输后端文件（无嵌套）
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/*"  # 只传 backend 里的内容（app.js、routes 等）
          target: "/var/www/programming-tools/backend"  # 内容直接落地到 backend

      # 验证：确保无嵌套且文件存在
      - name: 验证服务器目录结构
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "=== 前端目录（应直接看到 index.html、assets） ==="
            ls -la /var/www/programming-tools/frontend
            echo "=== 后端目录（应直接看到 app.js、routes） ==="
            ls -la /var/www/programming-tools/backend

      # 启动服务
      - name: 启动服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/programming-tools/backend
            npm install
            npm install -g pm2 || true
            pm2 restart app.js || pm2 start app.js
            sudo systemctl restart caddy