name: 部署到服务器（最终正确版）
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # 前端构建：路径为 frontend，确保 build 后生成 dist
      - name: 构建前端
        run: |
          cd frontend
          npm install
          npm run build

      # 后端准备：路径为 backend，安装生产依赖
      - name: 准备后端
        run: |
          cd backend
          npm install --production

      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            PROJECT_DIR="/var/www/programming-tools"
            mkdir -p $PROJECT_DIR/frontend $PROJECT_DIR/backend
            
            # 清理旧文件
            rm -rf $PROJECT_DIR/frontend/dist
            rm -rf $PROJECT_DIR/backend/*
            
            # 复制新文件（路径完全匹配）
            cp -r /github/workspace/frontend/dist $PROJECT_DIR/frontend/
            cp -r /github/workspace/backend/* $PROJECT_DIR/backend/
            
            # 启动后端（确认入口文件是 app.js）
            cd $PROJECT_DIR/backend
            npm install -g pm2
            pm2 restart app.js || pm2 start app.js  # 若入口是 server.js，替换为 server.js
            
            sudo systemctl restart caddy