name: 极简部署
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 构建前端 + 准备环境
        run: |
          # 安装 Node 并构建前端
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          cd frontend && npm install && npm run build && cd ..
          
          # 配置 SSH（免密登录服务器）
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: 传输文件并启动服务
        run: |
          # 传输前端 dist 到服务器 frontend 目录
          scp -P ${{ secrets.SERVER_PORT }} -r frontend/dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/programming-tools/frontend/
          
          # 传输后端文件到服务器 backend 目录
          scp -P ${{ secrets.SERVER_PORT }} -r backend/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/programming-tools/backend/
          
          # 通过 SSH 登录服务器并启动服务
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /var/www/programming-tools/backend
            npm install
            npm install -g pm2 || true
            pm2 restart app.js || pm2 start app.js
            sudo systemctl restart caddy
          EOF