name: 最终部署（修复路径映射）
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'

      - name: 构建前端
        run: |
          cd frontend
          npm install
          npm run build
          ls -la dist

      - name: 确认后端目录
        run: |
          cd backend
          ls -la

      - name: 部署到服务器（使用相对路径）
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 60s
          script: |
            PROJECT_DIR="/var/www/programming-tools"
            mkdir -p $PROJECT_DIR/frontend $PROJECT_DIR/backend
            
            # 核心：用相对路径复制文件
            cp -r frontend/dist $PROJECT_DIR/frontend/
            cp -r backend/* $PROJECT_DIR/backend/
            
            # 验证文件是否复制成功
            echo "服务器 frontend/dist 内容："
            ls -la $PROJECT_DIR/frontend/dist
            echo "服务器 backend 内容："
            ls -la $PROJECT_DIR/backend
            
            # 启动服务
            cd $PROJECT_DIR/backend
            npm install -g pm2 || true
            pm2 restart app.js || pm2 start app.js
            sudo systemctl restart caddy